### ISSUE TITLE
Unexpected precondition failure

### ISSUE THREAD

**Issue by darioncassel** [facebookexperimental/MIRAI#216]
## Issue

Precondition fails for contract with new name mangling scheme.

## Steps to Reproduce

```
#![feature(type_alias_enum_variants)]
#[macro_use]
extern crate mirai_annotations;

pub mod foreign_contracts {
    pub mod core {
        pub mod num {
            pub mod implement_u32 {
                pub fn max_value() -> u32 {
                    u32::max_value()
                }
            }
        }
    }
}

pub fn test1(size: u32) -> u32 {
    precondition!(size <= u32::max_value());
    size
}

pub fn test() {
    test1(100);
}

fn main() {
    test();
}
```

## Expected Behavior

No warnings should be issued.

## Actual Results

```
warning: possible unsatisfied precondition
  --> examples/test5.rs:23:5
   |
23 |     test1(100);
   |     ^^^^^^^^^^
   |
note: related location
  --> examples/test5.rs:18:5
   |
18 |     precondition!(size <= u32::max_value());
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Environment

Rust version (rustc --version): `rustc 1.37.0-nightly (2fe7b3383 2019-06-19)`

**Comment by darioncassel** [comment]
The issue seems to be with the lack of underscore in the function name `pub fn max_value()', but an underscore should not be required.

**Comment by hermanventer** [comment]
What is happening here is that the standard contracts that are bundled with MIRAI have defined "max_value_" whereas the foreign contracts in the test case have defined "max_value". When MIRAI searches for a summary, it first tries the mangled name (max_value_) and since the summary store has an entry with this name, the summary for max_value defined in the test case is not was used.

The failure itself seems due to a self referential definition of max_value in the standard contracts definition.
