### ISSUE TITLE
Cloning loses track of analysis-specific information

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#611]
## Issue

Some analysis-specific information (e.g, model fields, tag fields) is not tracked properly when cloning happens, because the compiler, who generates the implementation of `clone`, does not know the existence of such fields.

This is not really an issue, as the behavior of tag/model fields is totally defined by the analyzer. But it would be nicer to have a mechanism to track such information.

## Steps to Reproduce

Run MIRAI on the following code:
``` rust
#[derive(Clone)]
struct Block {
    content: i32,
}

use mirai_annotations::TagPropagationSet;

struct TaintTagKind<const MASK: TagPropagationSet> {}

const TAINT_TAG_MASK: TagPropagationSet = tag_propagation_set!();

type TaintTag = TaintTagKind<TAINT_TAG_MASK>;

pub fn main() {
    let a = Block { content: 0 };
    add_tag!(&a, TaintTag);
    let b = a.clone();
    verify!(has_tag!(&b, TaintTag));
}
```

## Expected Behavior

The program contains no bugs, so MIRAI is supposed to report no errors.

## Actual Results

MIRAI reports a provably false verification condition:
```
error: provably false verification condition
   --> src/main.rs:665:5
    |
665 |     verify!(has_tag!(&b, TaintTag));
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

## Environment

rustc 1.46.0-nightly (2753fab7c 2020-07-05)

**Comment by hermanventer** [comment]
Cloning is very special little snowflake. It can be arbitrary code and the in the standard library these functions are often not inlined so no MIR is available for them. Because they are so generic and arbitrary, it is also not really feasible to just add entries for them in foreign contracts.

I suspect we'll have to handle them by detecting that a function is a Clone method and then adding special handling that ensures that model fields and tag fields are copied into the clone. It should be noted that if the clone method just invokes a struct copy, these fields probably will get copied because they are just like any other non primitive elements to the abstract interpreter.

**Comment by stonebuddha** [comment]
> It should be noted that if the clone method just invokes a struct copy, these fields probably will get copied because they are just like any other non primitive elements to the abstract interpreter.

Yes, I experimented with copyable structs and MIRAI worked properly.
