### ISSUE TITLE
Emit a warning when running MIRAI in release mode

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#625]
## Issue

MIRAI currently uses some incomplete features of Rust (e.g., const generics) for carrying out tag analysis. It might become a concern if software developers don't want such incomplete features in release builds.

MIRAI could simply emit a warning (or even an error) when it is used to compile a project in release mode.

**Comment by hermanventer** [comment]
Release mode is also undesirable because it does not include code for integer overflow checking. There is no good reason for running MIRAI on a release build. Not trusting the correctness of the compiler in release mode, is not an option for us since we depend on the compiler's correctness in a myriad ways and running MIRAI during the release build is not going to add much security,

**Comment by hermanventer** [comment]
Now that the preferred way to run MIRAI is via `cargo mirai`, this is no longer much of an issue.
